### ISSUE TITLE
Uninitialized constant Nori::StringUtils

### ISSUE THREAD

**Issue by dmrwebdev** [savonrb/nori#104]
In the documentation the ```converts_tags_to``` example shows using a module named Nori::StringUtils to transform hash keys, however this module does not appear to be available in the latest release (v2.7.0) but is present in main. 

Attempting to convert hash keys currently results in the error ```eval error: uninitialized constant Nori::StringUtils```.

**Comment by pcai** [comment]
You appear to be referencing the documentation on main, which, as you noted, includes commits not yet released on rubygems. 

Please instead refer to the documentation that corresponds with the release version you are using.

**Comment by dmrwebdev** [comment]
Apologies for that I was not paying close enough attention, thanks for the quick response.
