### ISSUE TITLE
Attributes are lost when parsing Nori::StringWithAttributes element

### ISSUE THREAD

**Issue by RayChenLDL** [savonrb/nori#105]
I am using the code below to parse a XML response to Hash. However, some attributes from a String element are missing from the Hash.

parser = Nori.new
response_hash = parser.parse(response.to_s)

e.g. the attribute "ByEasement" of "IsLegal" is lost when parsing the response.
\<IsLegal ByEasement="true">true\</IsLegal>

And more interesting, Nori does not convert "IsLegal" to Nori::StringWithAttributes
![image](https://github.com/user-attachments/assets/20d546c0-428c-459d-a8f6-63ff4746f35c)

Another example is:
\<GameTime category="zone1">2018-02-12T06:23:00\</GameTime>
Attribute "category" of "GameTime" is lost.

I am using 2.6.0

However, Nori parse all the rest of elements well, no attributes lost.

**Comment by pcai** [comment]
Can you provide the xml source for your first example? It's not clear to me 1) what the input is, 2) what the actual output is, 3) what the expected output is

For your second example `<GameTime category="zone1">2018-02-12T06:23:00</GameTime>` I'm looking at https://github.com/savonrb/nori?tab=readme-ov-file#advanced_typecasting and the problem seems to be the typecasting is automatically converting the child value to a DateTime object. DateTime objects can't have attributes. It's not clear to me what a "fix" would look like?

**Comment by RayChenLDL** [comment]
Thanks Peter for looking into this so quickly, appreciated it.

The input for the 1st example is: 
\<IsLegal ByEasement="true">true\</IsLegal>

The actual output is( the attribute "ByEasement" of "IsLegal" is lost )
![image](https://github.com/user-attachments/assets/d8452cfd-bd51-4557-9b01-adf5435c28be)

The expected output is(The element  "IsLegal" should have the attribute "ByEasement")
![image](https://github.com/user-attachments/assets/e9561623-d547-43bf-9cca-c7b04e5dd239)


I found if I change the value of "IsLegal" from "true" to "Atrue", Nori parser will work fine. I guess it might be caused by the  "IsLegal" element has the same value as its attibute "ByEasement", both are "true"? not sure.

**Comment by RayChenLDL** [comment]
For the 2nd example, I am wondering how/if we could avoid the automatic typecasting 
? In the project I am working on, we need the DateTime objects have some attributes.

**Comment by pcai** [comment]
check this section: https://github.com/savonrb/nori?tab=readme-ov-file#advanced_typecasting

`advanced_typecasting: false` seems worth a try. im not positive but you might get StringWithAttributes back which will have attributes

**Comment by RayChenLDL** [comment]
Thanks Peter, it is working now. when using advanced_typecasting: false

**Comment by olleolleolle** [comment]
@RayChenLDL That's good news! Can this issue be closed with this?

**Comment by RayChenLDL** [comment]
Sure, thanks

**Comment by RayChenLDL** [comment]
Sure, thanks
