### ISSUE TITLE
Empty items handing

### ISSUE THREAD

**Issue by dklimkin** [savonrb/nori#35]
This issue was first discussed here: https://github.com/savonrb/savon/issues/137

Opening under Nori as it is more relevant.

I'd like to revisit this please. This causes an issue for me, as I can not pass an object returned by the server back to it:

Gyoku.xml(nori.parse("\<xml/\>"))
=> "\<xml xsi:nil=\\"true\\"/\>"

The server-side accepts empty item, but not a nil. Based on [some discussions](http://stackoverflow.com/a/774234) I believe the empty item should be parsed as an empty string:

Current behavior:
 nori.parse("\<xml/\>") => {"xml"=>nil}

Expected behavior:
 nori.parse("\<xml/\>") => {"xml"=>""}

**Comment by tjarratt** [comment]
Just released the feature that @konstantinn added as Nori v2.6.0. Thank you everyone that helped contribute and continue to improve Nori :)

**Comment by nicholaschen** [comment]
Sorry, I don't think the fix that @konstantinn addresses our use case - as it allows you to cast it into an empty string, but doesn't allow for omission of that particular tag (in our case, there's a semantic difference between a value of empty vs. something not being present). Can we re-examine if it's possible to add something that avoids appending nil valued elements in the response entirely?
