### ISSUE TITLE
It ignores attributes when a child is a text node.

### ISSUE THREAD

**Issue by barberj** [savonrb/nori#59]
Original conversation with @tjarratt started in #50 

I'm working with a soap api that has xml text nodes with an attribute. I'm not sure how to pass the hash to savon to render this node correctly. Using nori parse to try and reverse engineer the hash from the xml i saw that it didn't return a hash with the attribute visible. 

This is apparently desired feature as i found a supporting spec [#L305](https://github.com/savonrb/nori/blob/master/spec/nori/nori_spec.rb#L305):

``` ruby
305       it "should ignore attributes when a child is a text node" do
306         xml = "<root attr1='1'>Stuff</root>"
307         expect(parse(xml)).to eq({ "root" => "Stuff" })
308       end
```

I feel this is incorrect and the attribute should not be ignored. How else can we pass attributes for nodes where the child is text?

**Comment by xurde** [comment]
I've found a problem while parsing this kind of attributes, and my guess is that it is related to this issue.

This is what I've seen while debugging: `{:total=>[<totalcode="EUR">166141</total>]}`
The original XML was like `<Total Code="EUR">166141</Total>`, so at some point it seems to be wrongly merging the first attribute with the element itself, producing the ignoring.
I'm still trying to find the bug in Nori's code.

**Comment by bdwyertech** [comment]
+1

**Comment by yllihv27** [comment]
What if I want to get the attributes value also?
Tried this
```
xml_parser = Nori.new
xml_parser.parse "<FareReference ResBookDesigCode='Q'>Value</FareReference>"
```

Result is 
`{"FareReference"=>"Value"}`

I wanted to retrieve ResBookDesigCode value also

**Comment by anirbanmu** [comment]
> 
> 
> What if I want to get the attributes value also?
> Tried this
> 
> ```
> xml_parser = Nori.new
> xml_parser.parse "<FareReference ResBookDesigCode='Q'>Value</FareReference>"
> ```
> 
> Result is
> `{"FareReference"=>"Value"}`
> 
> I wanted to retrieve ResBookDesigCode value also

I came to the issues here trying to find the answer to the same thing. I'm trying to use Savon with an API that returns tags that have attributes which defines what the text in the tags actually mean. I was trying to figure out how to not lose the attributes when converting the response body to a hash. Have you found any way?

**Comment by trezona-lecomte** [comment]
@yllihv27 @anirbanmu I had the same use-case and found the solution here: https://github.com/savonrb/nori/issues/50#issuecomment-22622159. You can access the attributes via the `Nori::StringWithAttributes#attributes` method.

**Comment by pcai** [comment]
Hi. I've updated the readme [here](https://github.com/savonrb/nori#noristringwithattributes) with examples of how to access attributes from a text node, since it's not super obvious from repl that the result is of type `Nori::StringWithAttributes#attributes`
