### ISSUE TITLE
Why add Hash#to_params

### ISSUE THREAD

**Issue by jcoleman** [savonrb/nori#65]
Is there a particularly reason by Nori defines Hash#to_params (and related methods)? This method doesn't seem to be used anywhere inside Nori or Savon, it's not in the README, and it doesn't seem to be related to XML parsing.

I'm wondering in particular because I have pull request into Rails with defines Hash#to_params (with a different meaning) since Rails already defines Hash#to_param with the same basic meaning as what to_params does in this project.

**Comment by tjarratt** [comment]
Hey @jcoleman -- sorry this took me so dang long to respond to. If I had to wager a guess, [by looking at the older refs that changed that file](https://github.com/savonrb/nori/commit/13a785a7), I would say that this came in from `Nori` being a fork of `Crack`.

You're absolutely right that `Nori` and `Savon` are not using it. Thanks for pointing this out. I just removed the extension in commit 4db35be.
